wandb_version: 1

exp_name:
  desc: null
  value: ppo_coo
seed:
  desc: null
  value: 1
torch_deterministic:
  desc: null
  value: true
cuda:
  desc: null
  value: true
track:
  desc: null
  value: true
wandb_project_name:
  desc: null
  value: Entombed-Coop
wandb_entity:
  desc: null
  value: null
capture_video:
  desc: null
  value: false
env_id:
  desc: null
  value: entombed_cooperative_v3
total_timesteps:
  desc: null
  value: 8000
learning_rate:
  desc: null
  value: 0.00025
num_envs:
  desc: null
  value: 8
num_steps:
  desc: null
  value: 128
anneal_lr:
  desc: null
  value: true
gamma:
  desc: null
  value: 0.99
gae_lambda:
  desc: null
  value: 0.95
num_minibatches:
  desc: null
  value: 4
update_epochs:
  desc: null
  value: 4
norm_adv:
  desc: null
  value: true
clip_coef:
  desc: null
  value: 0.1
clip_vloss:
  desc: null
  value: true
ent_coef:
  desc: null
  value: 0.01
vf_coef:
  desc: null
  value: 0.5
max_grad_norm:
  desc: null
  value: 0.5
target_kl:
  desc: null
  value: null
batch_size:
  desc: null
  value: 1024
minibatch_size:
  desc: null
  value: 256
_wandb:
  desc: null
  value:
    code_path: code/ppo_coop.py
    python_version: 3.10.12
    cli_version: 0.17.9
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1727366143
    t:
      1:
      - 1
      - 2
      - 3
      - 55
      2:
      - 1
      - 2
      - 3
      - 55
      3:
      - 13
      - 16
      - 23
      - 35
      4: 3.10.12
      5: 0.17.9
      8:
      - 5
      13: linux-x86_64
