wandb_version: 1

exp_name:
  desc: null
  value: dqn_atari
seed:
  desc: null
  value: 1
torch_deterministic:
  desc: null
  value: true
cuda:
  desc: null
  value: true
track:
  desc: null
  value: true
wandb_project_name:
  desc: null
  value: DQN
wandb_entity:
  desc: null
  value: null
capture_video:
  desc: null
  value: false
save_model:
  desc: null
  value: false
upload_model:
  desc: null
  value: false
hf_entity:
  desc: null
  value: ''
env_id:
  desc: null
  value: entombed_cooperative_v3
total_timesteps:
  desc: null
  value: 10000
learning_rate:
  desc: null
  value: 0.0001
num_envs:
  desc: null
  value: 16
buffer_size:
  desc: null
  value: 100
gamma:
  desc: null
  value: 0.99
tau:
  desc: null
  value: 1.0
target_network_frequency:
  desc: null
  value: 1000
batch_size:
  desc: null
  value: 32
start_e:
  desc: null
  value: 1
end_e:
  desc: null
  value: 0.01
exploration_fraction:
  desc: null
  value: 0.1
learning_starts:
  desc: null
  value: 0
train_frequency:
  desc: null
  value: 4
_wandb:
  desc: null
  value:
    code_path: code/dqn_atari.py
    python_version: 3.10.12
    cli_version: 0.17.9
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1727793260
    t:
      1:
      - 1
      - 2
      - 3
      - 55
      2:
      - 1
      - 2
      - 3
      - 55
      3:
      - 13
      - 16
      - 23
      - 35
      4: 3.10.12
      5: 0.17.9
      8:
      - 5
      13: linux-x86_64
